### PR TITLE
Corrected file path

### PR DESCRIPTION
**Pull request by stevepeak**
Sorry, my mistake! Cheers!

### CODE REVIEW

**Comment by anton-johansson** [comment]
That explains why no coverage report was submitted! However, no error in travis, strange...

**Comment by anton-johansson** [comment]
Now it looks like I can see coverage for the PR, but try this:
https://codecov.io/github/Viskan/landing-pages?branch=#11

It changes back to "master" directly. :(

**Comment by stevepeak** [comment]
That link wont get the pr results `branch=#11`. https://codecov.io/github/Viskan/landing-pages?ref=9c6ac5fac918625f29e0b37e585b3e852a3bf742 should do the trick, directly targeting the commit sha.

Travis claims the branch is `master` for pull requests, but Codecov recognizes its not "on" the mater but does not distinguish the branch name yet (which I'll make note of)

Thanks :)

**Comment by anton-johansson** [comment]
Well, lcov does not have support for branch coverage, right? The branch
coverage is worth more than correct color alignments. :D

**Comment by stevepeak** [comment]
lol this is the case unfortunately.  I'm very open to suggestions :) I'm working with some others to help come up with work arounds for the time being.

**Comment by anton-johansson** [comment]
Allright, but for now I'll go back to coverage.json. :)

**Pull request closed without merging**
